services:
  x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    ports:
      - ${HOST_IP}:${WEB_PORT}:2053
    restart: always
    volumes:
      - ${APP_PATH}/data:/etc/x-ui/
      - ${APP_PATH}/cert:/root/cert/
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true